export interface ICreateTaskDTO {
	id?: string; // The id is optional because it is generated by the database
	name: string;
	description: string;
	hours: number;
	date: string | Date;
	userId: string;
}

export type IUpdateTaskDTO = Partial<ICreateTaskDTO>;

export interface ITask {
	id: string;
	name: string;
	description: string;
	hours: number;
	date: Date;
	createdAt: Date;
	updatedAt: Date;
	userId: string | null;
}
